[package]

name = "puppetfile"
version = "0.0.1"
authors = ["Robin Gloster <robin.gloster@mayflower.de>"]
license = "MIT"
description = "Puppetfile parser"
documentation = "http://mayflower.github.io/rust-puppetfile"
homepage = "https://github.com/Mayflower/rust-puppetfile"
repository = "https://github.com/Mayflower/rust-puppetfile"
readme = "README.md"
keywords = ["puppetfile", "parser", "r10k"]

[dependencies]
semver = "0.1.3"
url = "0.2.6"
hyper = "0.0.16"
