[package]

name = "puppetfile"
version = "0.0.0"
authors = ["Robin Gloster <robin.gloster@mayflower.de>"]


[dependencies.http]
git = "https://github.com/globin/rust-http"

[dependencies.semver]
git = "https://github.com/globin/semver"

[dependencies.url]
git = "https://github.com/servo/rust-url"
